[package]
name = "aabel-frequency"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aabel-hash = { path = "../aabel-hash" }
getrandom = "0.2.9"