[package]
name = "cuckoo-filter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aabel-hash = { path = "../../aabel-hash" }
log = { workspace = true }

[dev-dependencies]
env_logger = "0.10"
